apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-ubuntu
  name: pod-ubuntu
spec:
  containers:
  - image: docker.io/kthamel/kdev
    name: pod-ubuntu
    resources: {}
  imagePullSecrets:
    - name: regcred
