apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-ubuntu
  name: pod-ubuntu
spec:
  containers:
  - command:
    - sleep
    - "300"
    image: docker.io/kthamel/ubuntu-sleep
    name: pod-ubuntu
    resources: {}
  imagePullSecrets:
    - name: regcred
