apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-ubuntu
  name: pod-ubuntu
spec:
  containers:
  - command:
    - sleep
    - "300"
    image: ubuntu:latest
    name: pod-ubuntu
    resources: {}
  serviceAccountName: sa-dashboard
