apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota-develop
  namespace: develop
spec:
  hard:
    pods: "4"
    requests.cpu: "1"
    requests.memory: 5Gi
    limits.cpu: "2"
    limits.memory: 10Gi