apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-with-pv
  name: pod-with-pv
spec:
  containers:
  - command:
    - sleep
    - "300"
    image: ubuntu:latest
    name: pod-with-pv
    resources: {}
    volumeMounts:
      - mountPath: "/var"
        name: vol-dev
  volumes:
    - name: vol-dev
      persistentVolumeClaim:
        claimName: pvc-dev
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
