apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-volume
  name: pod-volume
spec:
  containers:
  - command:
    - sleep
    - "300"
    image: ubuntu:latest
    name: pod-volume
    resources: {}
    volumeMounts:
    - mountPath: /kdata
      name: pod-volume
  volumes:
  - name: pod-volume
    hostPath:
      path: /kubernetes
      type: Directory
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
