apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: monitoring-solution
spec:
  selector:
    matchLabels:
      app: monitoring-agent
  template:
    metadata:
      labels:
        app: monitoring-agent
    spec:
      containers:
        - name: monitoring-pod
          image:  ubuntu:latest
          command: ["sleep", "3600"]