apiVersion: v1
kind: ReplicationController
metadata:
  name: test-replication-controller
  labels:
    app: nginx-test
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        run: nginx
        name: nginx-pod
    spec:
      containers:
      - image: nginx
        name: nginx-container
  replicas: 3