apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: dev-nginx-pod
  name: dev-nginx-pod
spec:
  containers:
  - image: nginx
    name: dev-nginx-pod
    resources: {}
    envFrom:
      - secretRef:
          name: dev-login
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
